### ISSUE TITLE
Update Remix plugin to latest version

### ISSUE THREAD

**Issue by yann300** [Zokrates/zokrates-remix-plugin#46]
So it can be run in the remix vscode extension
The `createIframeClient` should be replace by `createClient` : https://github.com/Zokrates/zokrates-remix-plugin/blob/master/src/remix/RemixClient.ts#L11

You can find here an example implementation:
https://github.com/bunsenstraat/flattener/blob/master/src/Client.ts#L20
https://github.com/bunsenstraat/flattener/blob/master/src/Client.ts#L8
and the version to use https://github.com/bunsenstraat/flattener/blob/master/package.json#L9
```
"@remixproject/plugin": "0.3.19",
"@remixproject/plugin-webview": "0.3.19",
```

**Comment by dark64** [comment]
Hello @yann300,

I've made the changes needed and deployed it. I've tested it in vs code and it seems to work just fine!
I've opened a PR in the `remix-plugins-directory` repo: https://github.com/ethereum/remix-plugins-directory/pull/254

**Comment by yann300** [comment]
thanks for this,
@dark64 @Schaeff the plugin is now also available from the remix vscode extension https://marketplace.visualstudio.com/items?itemName=RemixProject.ethereum-remix
